llm:
  openai:
    provider: 'azure-openai'
    model_name: 'gpt-4o'
    end_point: 'https://llmops-amruth.openai.azure.com/'
    api_version: '2024-12-01-preview'
  
  openai_embeddings:
    provider: 'azure-openai'
    model_name: 'text-embedding-3-small'
    end_point: 'https://llmops-amruth.openai.azure.com/'
    api_version: '2024-12-01-preview'
  groq:
    provider: 'groq'
    model_name: 'deepseek-r1-distill-llama-70b'

pinecone:
  index_name: "medical-chatbot"
  dimension: 1536
  metric: 'cosine'
  cloud: 'aws'
  region: 'us-east-1'
  batch_size: 50
  embeddings_chunk_size: 64

